#!/usr/bin/env bash
# vim:fdm=marker fen

# aliases {{{1
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'

alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias l.='ls .* -d'

alias gv='gvim'
alias v='vim'
alias vi='vim -u NONE'

alias ssh="ssh -Y"

# export {{{1
export EDITOR='vim'
# export MANPAGER="vim -c MANPAGER -"
export TERM=xterm-256color

# setup tmux, please put it on $HOME/.shellrc {{{1
# which tmux > /dev/null 2>&1
# if [ $? -eq 0 ]; then
#   case $- in *i*)
#     [ -z "$TMUX" ] && exec $(TERM=xterm-256color tmux -2)
#   esac
# fi

